### ISSUE TITLE
You cannot make a crew with an all CAPS 5-letter Tag. (Ex: PLTUS will not work, but PLTS does) (IronAR)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#120]
**Describe the bug** *(A clear and concise description of what the bug is)*:
What I am assuming is the chat filter's filter on CAPS causes players to not be able to make crews with 5-letter tags have their tag in all CAPS. Most crews use CAPS for their tags as its an abbreviation, but after 4 letters it filters it. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Create a crew with a 5 letter tag in all CAPS. It cannot happen. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
21/2/2021

**Comment by TomLewis** [comment]
I scanned all the logs to find "PLTUS" used to find out exactly what was triggering it because the CAPS filter does not filter /crew, the caps filter filters:

```
Anti_Caps:
  Enabled: true
  Enabled_In_Commands: true
  Commands_To_Apply:
  - /tell
  - /pm
  - /t
  - /w
  - /r
  - /msg
  - /m
  - /whisper
  - /w
  - /c
  - /a
  - /mail
  - /me
  ```

But there wasn't a single mention of the word PLTUS (in all caps) at all in any of the logs entire history, it's never even been said in chat!

So I cant confirm it, and it makes no sense as it requires /crew to make a crew which is not in the list of commands that will be filtered for caps.

But I have inreaesd the Min_Caps_In_A_Row from 5 to 6 chars in the chat plugin globally even tho this makes no sense!
